version: "3"

services:
  web:
    build: .
    #command:
    volumes:
      - .:/code
    depends_on:
      - mariadb
    ports:
      - '8000:8000'
    links:
      - mariadb
  mariadb:
    image: "mariadb"
    env_file: database.env
    #volumes:
     # - "/var/lib/mysql/data:${MARIADB_DATA_DIR}"
      #- "/var/lib/mysql/logs:${MARIADB_LOG_DIR}"
      # - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "gregncl"
      MYSQL_DATABASE: "django"
      #MYSQL_USER: "${MYSQL_USER}"
      #MYSQL_PASSWORD: "${MYSQL_PASSWORD}"