# Generated by Django 4.0 on 2021-12-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['finished']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='descriptiom',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='complete',
            new_name='finished',
        ),
    ]
